version: "3.9"

services:
  frontend:
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    image: w1zdom/ai-summarizer-ui
    container_name: ai-summarizer
    ports:
      - "8080:80"

  backend:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: w1zdom/ai-summarizer-backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      MODEL: llama-3.3-70b-versatile
    secrets:
      - openai_api_base
      - openai_api_key
      - db_url
    depends_on:
      db:
        condition: service_healthy
    entrypoint: >
      sh -c "
      export OPENAI_API_BASE=$(cat /run/secrets/openai_api_base) &&
      export OPENAI_API_KEY=$(cat /run/secrets/openai_api_key) &&
      export DATABASE_URL=$(cat /run/secrets/db_url) &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "

  db:
    image: postgres:18
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    secrets:
      - db_user
      - db_password
      - postgres_db
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

secrets:
  openai_api_key:
    file: ./secrets/openai_api_key.txt
  openai_api_base:
    file: ./secrets/openai_api_base.txt
  db_url:
    file: ./secrets/db_url.txt
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  postgres_db:
    file: ./secrets/postgres_db.txt

volumes:
  postgres_data:
